<html lang="en">
<head>
    <title>Find your Pokemon!</title>
</head>
<body>
    <h1>Find your soul Pokémon!</h1>
    <p>Type your name to find the Pokémon that matches your soul!</p>
    <form action="/" method="get">
        <label for="name">
            Name:
            <input id="name" type="text" name="name" />
        </label>
        <input type="submit" value="Submit!">
    </form>

</body>
</html>
