<html lang="en">
<head>
    <title>Find your Pokemon!</title>
</head>
<body>
<h1>You don't have a soul Pokemon 🥺</h1>
<p>Don't worry, this does not mean you are a soulless person. It's just the decimal representation of your name is zero. 😛</p>
<p>Maybe try with another name!</p>
<form action="/" method="get">
    <label for="name">
        Name:
        <input id="name" type="text" name="name" />
    </label>
    <input type="submit" value="Submit!">
</form>

</body>
</html>
